# Generated by Django 5.0.6 on 2026-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_edited_at_message_is_edited_messageedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='call_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='call_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
