# Generated by Django 4.2.7 on 2026-10-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userprofile_handle_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageedit',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='messageedit',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='call_duration',
        ),
        migrations.RemoveField(
            model_name='message',
            name='call_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='call_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='handle',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='MessageEdit',
        ),
    ]
