# Generated by Django 4.2.7 on 2026-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
