# Generated by Django 4.2.7 on 2026-10-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_userprofile_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_duration',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('call_missed', 'Missed Call'), ('call_outgoing', 'Outgoing Call'), ('call_incoming', 'Incoming Call'), ('call_answered', 'Answered Call'), ('call_rejected', 'Rejected Call'), ('call_cancelled', 'Cancelled Call'), ('call_busy', 'Busy Call')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('missed', 'Missed'), ('answered', 'Answered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('busy', 'Busy'), ('timeout', 'Timeout')], default='missed', max_length=10),
        ),
    ]
