# Generated by Django 4.2.7 on 2026-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatflow_id_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ai_bot',
            field=models.BooleanField(default=False),
        ),
    ]
